# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=25)),
                ('office', models.CharField(max_length=200)),
                ('radius', models.CharField(max_length=5)),
            ],
        ),
    ]
